package com.meiyou.mapper;

import com.meiyou.pojo.ActivityLike;
import com.meiyou.pojo.ActivityLikeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ActivityLikeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_like
     *
     * @mbggenerated Sat Sep 07 09:28:45 CST 2019
     */
    int countByExample(ActivityLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_like
     *
     * @mbggenerated Sat Sep 07 09:28:45 CST 2019
     */
    int deleteByExample(ActivityLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_like
     *
     * @mbggenerated Sat Sep 07 09:28:45 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_like
     *
     * @mbggenerated Sat Sep 07 09:28:45 CST 2019
     */
    int insert(ActivityLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_like
     *
     * @mbggenerated Sat Sep 07 09:28:45 CST 2019
     */
    int insertSelective(ActivityLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_like
     *
     * @mbggenerated Sat Sep 07 09:28:45 CST 2019
     */
    List<ActivityLike> selectByExample(ActivityLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_like
     *
     * @mbggenerated Sat Sep 07 09:28:45 CST 2019
     */
    ActivityLike selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_like
     *
     * @mbggenerated Sat Sep 07 09:28:45 CST 2019
     */
    int updateByExampleSelective(@Param("record") ActivityLike record, @Param("example") ActivityLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_like
     *
     * @mbggenerated Sat Sep 07 09:28:45 CST 2019
     */
    int updateByExample(@Param("record") ActivityLike record, @Param("example") ActivityLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_like
     *
     * @mbggenerated Sat Sep 07 09:28:45 CST 2019
     */
    int updateByPrimaryKeySelective(ActivityLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_like
     *
     * @mbggenerated Sat Sep 07 09:28:45 CST 2019
     */
    int updateByPrimaryKey(ActivityLike record);
}