package com.meiyou.mapper;

import com.meiyou.pojo.ActivityReport;
import com.meiyou.pojo.ActivityReportExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ActivityReportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_report
     *
     * @mbggenerated Thu Aug 29 09:29:43 CST 2019
     */
    int countByExample(ActivityReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_report
     *
     * @mbggenerated Thu Aug 29 09:29:43 CST 2019
     */
    int deleteByExample(ActivityReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_report
     *
     * @mbggenerated Thu Aug 29 09:29:43 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_report
     *
     * @mbggenerated Thu Aug 29 09:29:43 CST 2019
     */
    int insert(ActivityReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_report
     *
     * @mbggenerated Thu Aug 29 09:29:43 CST 2019
     */
    int insertSelective(ActivityReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_report
     *
     * @mbggenerated Thu Aug 29 09:29:43 CST 2019
     */
    List<ActivityReport> selectByExample(ActivityReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_report
     *
     * @mbggenerated Thu Aug 29 09:29:43 CST 2019
     */
    ActivityReport selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_report
     *
     * @mbggenerated Thu Aug 29 09:29:43 CST 2019
     */
    int updateByExampleSelective(@Param("record") ActivityReport record, @Param("example") ActivityReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_report
     *
     * @mbggenerated Thu Aug 29 09:29:43 CST 2019
     */
    int updateByExample(@Param("record") ActivityReport record, @Param("example") ActivityReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_report
     *
     * @mbggenerated Thu Aug 29 09:29:43 CST 2019
     */
    int updateByPrimaryKeySelective(ActivityReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_report
     *
     * @mbggenerated Thu Aug 29 09:29:43 CST 2019
     */
    int updateByPrimaryKey(ActivityReport record);
}