package com.meiyou.mapper;

import com.meiyou.pojo.ClubBuy;
import com.meiyou.pojo.ClubBuyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ClubBuyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_buy
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    int countByExample(ClubBuyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_buy
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    int deleteByExample(ClubBuyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_buy
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_buy
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    int insert(ClubBuy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_buy
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    int insertSelective(ClubBuy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_buy
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    List<ClubBuy> selectByExample(ClubBuyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_buy
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    ClubBuy selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_buy
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    int updateByExampleSelective(@Param("record") ClubBuy record, @Param("example") ClubBuyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_buy
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    int updateByExample(@Param("record") ClubBuy record, @Param("example") ClubBuyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_buy
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    int updateByPrimaryKeySelective(ClubBuy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_buy
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    int updateByPrimaryKey(ClubBuy record);
}