package com.meiyou.mapper;

import com.meiyou.pojo.ClubStar;
import com.meiyou.pojo.ClubStarExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ClubStarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_star
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    int countByExample(ClubStarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_star
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    int deleteByExample(ClubStarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_star
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_star
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    int insert(ClubStar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_star
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    int insertSelective(ClubStar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_star
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    List<ClubStar> selectByExample(ClubStarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_star
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    ClubStar selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_star
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    int updateByExampleSelective(@Param("record") ClubStar record, @Param("example") ClubStarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_star
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    int updateByExample(@Param("record") ClubStar record, @Param("example") ClubStarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_star
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    int updateByPrimaryKeySelective(ClubStar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_star
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    int updateByPrimaryKey(ClubStar record);
}