package com.meiyou.mapper;

import com.meiyou.pojo.CommentLike;
import com.meiyou.pojo.CommentLikeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CommentLikeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_like
     *
     * @mbggenerated Fri Aug 23 17:39:47 CST 2019
     */
    int countByExample(CommentLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_like
     *
     * @mbggenerated Fri Aug 23 17:39:47 CST 2019
     */
    int deleteByExample(CommentLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_like
     *
     * @mbggenerated Fri Aug 23 17:39:47 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_like
     *
     * @mbggenerated Fri Aug 23 17:39:47 CST 2019
     */
    int insert(CommentLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_like
     *
     * @mbggenerated Fri Aug 23 17:39:47 CST 2019
     */
    int insertSelective(CommentLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_like
     *
     * @mbggenerated Fri Aug 23 17:39:47 CST 2019
     */
    List<CommentLike> selectByExample(CommentLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_like
     *
     * @mbggenerated Fri Aug 23 17:39:47 CST 2019
     */
    CommentLike selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_like
     *
     * @mbggenerated Fri Aug 23 17:39:47 CST 2019
     */
    int updateByExampleSelective(@Param("record") CommentLike record, @Param("example") CommentLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_like
     *
     * @mbggenerated Fri Aug 23 17:39:47 CST 2019
     */
    int updateByExample(@Param("record") CommentLike record, @Param("example") CommentLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_like
     *
     * @mbggenerated Fri Aug 23 17:39:47 CST 2019
     */
    int updateByPrimaryKeySelective(CommentLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_like
     *
     * @mbggenerated Fri Aug 23 17:39:47 CST 2019
     */
    int updateByPrimaryKey(CommentLike record);
}