package com.meiyou.mapper;

import com.meiyou.pojo.RedPacket;
import com.meiyou.pojo.RedPacketExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RedPacketMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    int countByExample(RedPacketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    int deleteByExample(RedPacketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    int insert(RedPacket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    int insertSelective(RedPacket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    List<RedPacket> selectByExample(RedPacketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    RedPacket selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    int updateByExampleSelective(@Param("record") RedPacket record, @Param("example") RedPacketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    int updateByExample(@Param("record") RedPacket record, @Param("example") RedPacketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    int updateByPrimaryKeySelective(RedPacket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    int updateByPrimaryKey(RedPacket record);
}