package com.meiyou.mapper;

import com.meiyou.pojo.UserReport;
import com.meiyou.pojo.UserReportExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserReportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_report
     *
     * @mbggenerated Fri Aug 30 14:41:10 CST 2019
     */
    int countByExample(UserReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_report
     *
     * @mbggenerated Fri Aug 30 14:41:10 CST 2019
     */
    int deleteByExample(UserReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_report
     *
     * @mbggenerated Fri Aug 30 14:41:10 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_report
     *
     * @mbggenerated Fri Aug 30 14:41:10 CST 2019
     */
    int insert(UserReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_report
     *
     * @mbggenerated Fri Aug 30 14:41:10 CST 2019
     */
    int insertSelective(UserReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_report
     *
     * @mbggenerated Fri Aug 30 14:41:10 CST 2019
     */
    List<UserReport> selectByExample(UserReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_report
     *
     * @mbggenerated Fri Aug 30 14:41:10 CST 2019
     */
    UserReport selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_report
     *
     * @mbggenerated Fri Aug 30 14:41:10 CST 2019
     */
    int updateByExampleSelective(@Param("record") UserReport record, @Param("example") UserReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_report
     *
     * @mbggenerated Fri Aug 30 14:41:10 CST 2019
     */
    int updateByExample(@Param("record") UserReport record, @Param("example") UserReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_report
     *
     * @mbggenerated Fri Aug 30 14:41:10 CST 2019
     */
    int updateByPrimaryKeySelective(UserReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_report
     *
     * @mbggenerated Fri Aug 30 14:41:10 CST 2019
     */
    int updateByPrimaryKey(UserReport record);
}