package com.meiyou.mapper;

import com.meiyou.pojo.VideoChat;
import com.meiyou.pojo.VideoChatExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VideoChatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_chat
     *
     * @mbggenerated Sat Aug 24 22:37:36 CST 2019
     */
    int countByExample(VideoChatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_chat
     *
     * @mbggenerated Sat Aug 24 22:37:36 CST 2019
     */
    int deleteByExample(VideoChatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_chat
     *
     * @mbggenerated Sat Aug 24 22:37:36 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_chat
     *
     * @mbggenerated Sat Aug 24 22:37:36 CST 2019
     */
    int insert(VideoChat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_chat
     *
     * @mbggenerated Sat Aug 24 22:37:36 CST 2019
     */
    int insertSelective(VideoChat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_chat
     *
     * @mbggenerated Sat Aug 24 22:37:36 CST 2019
     */
    List<VideoChat> selectByExample(VideoChatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_chat
     *
     * @mbggenerated Sat Aug 24 22:37:36 CST 2019
     */
    VideoChat selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_chat
     *
     * @mbggenerated Sat Aug 24 22:37:36 CST 2019
     */
    int updateByExampleSelective(@Param("record") VideoChat record, @Param("example") VideoChatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_chat
     *
     * @mbggenerated Sat Aug 24 22:37:36 CST 2019
     */
    int updateByExample(@Param("record") VideoChat record, @Param("example") VideoChatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_chat
     *
     * @mbggenerated Sat Aug 24 22:37:36 CST 2019
     */
    int updateByPrimaryKeySelective(VideoChat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_chat
     *
     * @mbggenerated Sat Aug 24 22:37:36 CST 2019
     */
    int updateByPrimaryKey(VideoChat record);
}