package com.meiyou.pojo;

import java.util.Date;
import java.util.List;

public class Activity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.id
     *
     * @mbggenerated Wed Aug 21 14:28:33 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.create_time
     *
     * @mbggenerated Wed Aug 21 14:28:33 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.update_time
     *
     * @mbggenerated Wed Aug 21 14:28:33 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.publish_id
     *
     * @mbggenerated Wed Aug 21 14:28:33 CST 2019
     */
    private Integer publishId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.imgs_url
     *
     * @mbggenerated Wed Aug 21 14:28:33 CST 2019
     */
    private String imgsUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.content
     *
     * @mbggenerated Wed Aug 21 14:28:33 CST 2019
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.read_num
     *
     * @mbggenerated Wed Aug 21 14:28:33 CST 2019
     */
    private Integer readNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.like_num
     *
     * @mbggenerated Wed Aug 21 14:28:33 CST 2019
     */
    private Integer likeNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.commont_num
     *
     * @mbggenerated Wed Aug 21 14:28:33 CST 2019
     */
    private Integer commontNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.bool_close
     *
     * @mbggenerated Wed Aug 21 14:28:33 CST 2019
     */
    private Boolean boolClose;

    /**
     * hzy
     * 发布的用户
     */
    private User user;

    /**
     * hzy
     * 阅读数
     */
    private List<Read> readList;

    /**
     * hzy
     * 点赞数
     */
    private List<ActivityLike> likeList;



    /**
     * hzy
     * 评论数
     */
    private List<Comment> commentList;

    @Override
    public String toString() {
        return "Activity{" +
                "id=" + id +
                ", createTime=" + createTime +
                ", updateTime=" + updateTime +
                ", publishId=" + publishId +
                ", imgsUrl='" + imgsUrl + '\'' +
                ", content='" + content + '\'' +
                ", readNum=" + readNum +
                ", likeNum=" + likeNum +
                ", commontNum=" + commontNum +
                ", boolClose=" + boolClose +
                ", user=" + user +
                ", readList=" + readList +
                ", likeList=" + likeList +
                ", commentList=" + commentList +
                '}';
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public Integer getPublishId() {
        return publishId;
    }

    public void setPublishId(Integer publishId) {
        this.publishId = publishId;
    }

    public String getImgsUrl() {
        return imgsUrl;
    }

    public void setImgsUrl(String imgsUrl) {
        this.imgsUrl = imgsUrl;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public Integer getReadNum() {
        return readNum;
    }

    public void setReadNum(Integer readNum) {
        this.readNum = readNum;
    }

    public Integer getLikeNum() {
        return likeNum;
    }

    public void setLikeNum(Integer likeNum) {
        this.likeNum = likeNum;
    }

    public Integer getCommontNum() {
        return commontNum;
    }

    public void setCommontNum(Integer commontNum) {
        this.commontNum = commontNum;
    }

    public Boolean getBoolClose() {
        return boolClose;
    }

    public void setBoolClose(Boolean boolClose) {
        this.boolClose = boolClose;
    }

    public List<Read> getReadList() {
        return readList;
    }

    public void setReadList(List<Read> readList) {
        this.readList = readList;
    }

    public List<ActivityLike> getLikeList() {
        return likeList;
    }

    public void setLikeList(List<ActivityLike> likeList) {
        this.likeList = likeList;
    }

    public List<Comment> getCommentList() {
        return commentList;
    }

    public void setCommentList(List<Comment> commentList) {
        this.commentList = commentList;
    }


    public Activity() {
    }

    public Activity(Integer id, Date createTime, Date updateTime, Integer publishId, String imgsUrl, String content, Integer readNum, Integer likeNum, Integer commontNum, Boolean boolClose, User user, List<Read> readList, List<ActivityLike> likeList, List<Comment> commentList) {
        this.id = id;
        this.createTime = createTime;
        this.updateTime = updateTime;
        this.publishId = publishId;
        this.imgsUrl = imgsUrl;
        this.content = content;
        this.readNum = readNum;
        this.likeNum = likeNum;
        this.commontNum = commontNum;
        this.boolClose = boolClose;
        this.user = user;
        this.readList = readList;
        this.likeList = likeList;
        this.commentList = commentList;
    }
}