package com.meiyou.pojo;

import java.util.Date;

public class ActivityLike {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_like.id
     *
     * @mbggenerated Sat Sep 07 09:28:45 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_like.create_time
     *
     * @mbggenerated Sat Sep 07 09:28:45 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_like.update_time
     *
     * @mbggenerated Sat Sep 07 09:28:45 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_like.activity_id
     *
     * @mbggenerated Sat Sep 07 09:28:45 CST 2019
     */
    private Integer activityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_like.like_id
     *
     * @mbggenerated Sat Sep 07 09:28:45 CST 2019
     */
    private Integer likeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_like.bool_see
     *
     * @mbggenerated Sat Sep 07 09:28:45 CST 2019
     */
    private Boolean boolSee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_like.bool_close
     *
     * @mbggenerated Sat Sep 07 09:28:45 CST 2019
     */
    private Boolean boolClose;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_like.id
     *
     * @return the value of activity_like.id
     *
     * @mbggenerated Sat Sep 07 09:28:45 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_like.id
     *
     * @param id the value for activity_like.id
     *
     * @mbggenerated Sat Sep 07 09:28:45 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_like.create_time
     *
     * @return the value of activity_like.create_time
     *
     * @mbggenerated Sat Sep 07 09:28:45 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_like.create_time
     *
     * @param createTime the value for activity_like.create_time
     *
     * @mbggenerated Sat Sep 07 09:28:45 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_like.update_time
     *
     * @return the value of activity_like.update_time
     *
     * @mbggenerated Sat Sep 07 09:28:45 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_like.update_time
     *
     * @param updateTime the value for activity_like.update_time
     *
     * @mbggenerated Sat Sep 07 09:28:45 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_like.activity_id
     *
     * @return the value of activity_like.activity_id
     *
     * @mbggenerated Sat Sep 07 09:28:45 CST 2019
     */
    public Integer getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_like.activity_id
     *
     * @param activityId the value for activity_like.activity_id
     *
     * @mbggenerated Sat Sep 07 09:28:45 CST 2019
     */
    public void setActivityId(Integer activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_like.like_id
     *
     * @return the value of activity_like.like_id
     *
     * @mbggenerated Sat Sep 07 09:28:45 CST 2019
     */
    public Integer getLikeId() {
        return likeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_like.like_id
     *
     * @param likeId the value for activity_like.like_id
     *
     * @mbggenerated Sat Sep 07 09:28:45 CST 2019
     */
    public void setLikeId(Integer likeId) {
        this.likeId = likeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_like.bool_see
     *
     * @return the value of activity_like.bool_see
     *
     * @mbggenerated Sat Sep 07 09:28:45 CST 2019
     */
    public Boolean getBoolSee() {
        return boolSee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_like.bool_see
     *
     * @param boolSee the value for activity_like.bool_see
     *
     * @mbggenerated Sat Sep 07 09:28:45 CST 2019
     */
    public void setBoolSee(Boolean boolSee) {
        this.boolSee = boolSee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_like.bool_close
     *
     * @return the value of activity_like.bool_close
     *
     * @mbggenerated Sat Sep 07 09:28:45 CST 2019
     */
    public Boolean getBoolClose() {
        return boolClose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_like.bool_close
     *
     * @param boolClose the value for activity_like.bool_close
     *
     * @mbggenerated Sat Sep 07 09:28:45 CST 2019
     */
    public void setBoolClose(Boolean boolClose) {
        this.boolClose = boolClose;
    }
}