package com.meiyou.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AppointmentExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table appointment
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table appointment
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table appointment
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    protected List<Criteria> oredCriteria;

    private Integer pageNo;
    private Integer pageSize;

    public Integer getPageNo() {
        return pageNo;
    }

    public void setPageNo(Integer pageNo) {
        this.pageNo = pageNo;
    }

    public Integer getPageSize() {
        return pageSize;
    }

    public void setPageSize(Integer pageSize) {
        this.pageSize = pageSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    public AppointmentExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table appointment
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andPublisherIdIsNull() {
            addCriterion("publisher_id is null");
            return (Criteria) this;
        }

        public Criteria andPublisherIdIsNotNull() {
            addCriterion("publisher_id is not null");
            return (Criteria) this;
        }

        public Criteria andPublisherIdEqualTo(Integer value) {
            addCriterion("publisher_id =", value, "publisherId");
            return (Criteria) this;
        }

        public Criteria andPublisherIdNotEqualTo(Integer value) {
            addCriterion("publisher_id <>", value, "publisherId");
            return (Criteria) this;
        }

        public Criteria andPublisherIdGreaterThan(Integer value) {
            addCriterion("publisher_id >", value, "publisherId");
            return (Criteria) this;
        }

        public Criteria andPublisherIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("publisher_id >=", value, "publisherId");
            return (Criteria) this;
        }

        public Criteria andPublisherIdLessThan(Integer value) {
            addCriterion("publisher_id <", value, "publisherId");
            return (Criteria) this;
        }

        public Criteria andPublisherIdLessThanOrEqualTo(Integer value) {
            addCriterion("publisher_id <=", value, "publisherId");
            return (Criteria) this;
        }

        public Criteria andPublisherIdIn(List<Integer> values) {
            addCriterion("publisher_id in", values, "publisherId");
            return (Criteria) this;
        }

        public Criteria andPublisherIdNotIn(List<Integer> values) {
            addCriterion("publisher_id not in", values, "publisherId");
            return (Criteria) this;
        }

        public Criteria andPublisherIdBetween(Integer value1, Integer value2) {
            addCriterion("publisher_id between", value1, value2, "publisherId");
            return (Criteria) this;
        }

        public Criteria andPublisherIdNotBetween(Integer value1, Integer value2) {
            addCriterion("publisher_id not between", value1, value2, "publisherId");
            return (Criteria) this;
        }

        public Criteria andAppointAddressIsNull() {
            addCriterion("appoint_address is null");
            return (Criteria) this;
        }

        public Criteria andAppointAddressIsNotNull() {
            addCriterion("appoint_address is not null");
            return (Criteria) this;
        }

        public Criteria andAppointAddressEqualTo(String value) {
            addCriterion("appoint_address =", value, "appointAddress");
            return (Criteria) this;
        }

        public Criteria andAppointAddressNotEqualTo(String value) {
            addCriterion("appoint_address <>", value, "appointAddress");
            return (Criteria) this;
        }

        public Criteria andAppointAddressGreaterThan(String value) {
            addCriterion("appoint_address >", value, "appointAddress");
            return (Criteria) this;
        }

        public Criteria andAppointAddressGreaterThanOrEqualTo(String value) {
            addCriterion("appoint_address >=", value, "appointAddress");
            return (Criteria) this;
        }

        public Criteria andAppointAddressLessThan(String value) {
            addCriterion("appoint_address <", value, "appointAddress");
            return (Criteria) this;
        }

        public Criteria andAppointAddressLessThanOrEqualTo(String value) {
            addCriterion("appoint_address <=", value, "appointAddress");
            return (Criteria) this;
        }

        public Criteria andAppointAddressLike(String value) {
            addCriterion("appoint_address like", value, "appointAddress");
            return (Criteria) this;
        }

        public Criteria andAppointAddressNotLike(String value) {
            addCriterion("appoint_address not like", value, "appointAddress");
            return (Criteria) this;
        }

        public Criteria andAppointAddressIn(List<String> values) {
            addCriterion("appoint_address in", values, "appointAddress");
            return (Criteria) this;
        }

        public Criteria andAppointAddressNotIn(List<String> values) {
            addCriterion("appoint_address not in", values, "appointAddress");
            return (Criteria) this;
        }

        public Criteria andAppointAddressBetween(String value1, String value2) {
            addCriterion("appoint_address between", value1, value2, "appointAddress");
            return (Criteria) this;
        }

        public Criteria andAppointAddressNotBetween(String value1, String value2) {
            addCriterion("appoint_address not between", value1, value2, "appointAddress");
            return (Criteria) this;
        }

        public Criteria andAppointTimeIsNull() {
            addCriterion("appoint_time is null");
            return (Criteria) this;
        }

        public Criteria andAppointTimeIsNotNull() {
            addCriterion("appoint_time is not null");
            return (Criteria) this;
        }

        public Criteria andAppointTimeEqualTo(String value) {
            addCriterion("appoint_time =", value, "appointTime");
            return (Criteria) this;
        }

        public Criteria andAppointTimeNotEqualTo(String value) {
            addCriterion("appoint_time <>", value, "appointTime");
            return (Criteria) this;
        }

        public Criteria andAppointTimeGreaterThan(String value) {
            addCriterion("appoint_time >", value, "appointTime");
            return (Criteria) this;
        }

        public Criteria andAppointTimeGreaterThanOrEqualTo(String value) {
            addCriterion("appoint_time >=", value, "appointTime");
            return (Criteria) this;
        }

        public Criteria andAppointTimeLessThan(String value) {
            addCriterion("appoint_time <", value, "appointTime");
            return (Criteria) this;
        }

        public Criteria andAppointTimeLessThanOrEqualTo(String value) {
            addCriterion("appoint_time <=", value, "appointTime");
            return (Criteria) this;
        }

        public Criteria andAppointTimeLike(String value) {
            addCriterion("appoint_time like", value, "appointTime");
            return (Criteria) this;
        }

        public Criteria andAppointTimeNotLike(String value) {
            addCriterion("appoint_time not like", value, "appointTime");
            return (Criteria) this;
        }

        public Criteria andAppointTimeIn(List<String> values) {
            addCriterion("appoint_time in", values, "appointTime");
            return (Criteria) this;
        }

        public Criteria andAppointTimeNotIn(List<String> values) {
            addCriterion("appoint_time not in", values, "appointTime");
            return (Criteria) this;
        }

        public Criteria andAppointTimeBetween(String value1, String value2) {
            addCriterion("appoint_time between", value1, value2, "appointTime");
            return (Criteria) this;
        }

        public Criteria andAppointTimeNotBetween(String value1, String value2) {
            addCriterion("appoint_time not between", value1, value2, "appointTime");
            return (Criteria) this;
        }

        public Criteria andAppointContextIsNull() {
            addCriterion("appoint_context is null");
            return (Criteria) this;
        }

        public Criteria andAppointContextIsNotNull() {
            addCriterion("appoint_context is not null");
            return (Criteria) this;
        }

        public Criteria andAppointContextEqualTo(String value) {
            addCriterion("appoint_context =", value, "appointContext");
            return (Criteria) this;
        }

        public Criteria andAppointContextNotEqualTo(String value) {
            addCriterion("appoint_context <>", value, "appointContext");
            return (Criteria) this;
        }

        public Criteria andAppointContextGreaterThan(String value) {
            addCriterion("appoint_context >", value, "appointContext");
            return (Criteria) this;
        }

        public Criteria andAppointContextGreaterThanOrEqualTo(String value) {
            addCriterion("appoint_context >=", value, "appointContext");
            return (Criteria) this;
        }

        public Criteria andAppointContextLessThan(String value) {
            addCriterion("appoint_context <", value, "appointContext");
            return (Criteria) this;
        }

        public Criteria andAppointContextLessThanOrEqualTo(String value) {
            addCriterion("appoint_context <=", value, "appointContext");
            return (Criteria) this;
        }

        public Criteria andAppointContextLike(String value) {
            addCriterion("appoint_context like", value, "appointContext");
            return (Criteria) this;
        }

        public Criteria andAppointContextNotLike(String value) {
            addCriterion("appoint_context not like", value, "appointContext");
            return (Criteria) this;
        }

        public Criteria andAppointContextIn(List<String> values) {
            addCriterion("appoint_context in", values, "appointContext");
            return (Criteria) this;
        }

        public Criteria andAppointContextNotIn(List<String> values) {
            addCriterion("appoint_context not in", values, "appointContext");
            return (Criteria) this;
        }

        public Criteria andAppointContextBetween(String value1, String value2) {
            addCriterion("appoint_context between", value1, value2, "appointContext");
            return (Criteria) this;
        }

        public Criteria andAppointContextNotBetween(String value1, String value2) {
            addCriterion("appoint_context not between", value1, value2, "appointContext");
            return (Criteria) this;
        }

        public Criteria andNeedNumberIsNull() {
            addCriterion("need_number is null");
            return (Criteria) this;
        }

        public Criteria andNeedNumberIsNotNull() {
            addCriterion("need_number is not null");
            return (Criteria) this;
        }

        public Criteria andNeedNumberEqualTo(Integer value) {
            addCriterion("need_number =", value, "needNumber");
            return (Criteria) this;
        }

        public Criteria andNeedNumberNotEqualTo(Integer value) {
            addCriterion("need_number <>", value, "needNumber");
            return (Criteria) this;
        }

        public Criteria andNeedNumberGreaterThan(Integer value) {
            addCriterion("need_number >", value, "needNumber");
            return (Criteria) this;
        }

        public Criteria andNeedNumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("need_number >=", value, "needNumber");
            return (Criteria) this;
        }

        public Criteria andNeedNumberLessThan(Integer value) {
            addCriterion("need_number <", value, "needNumber");
            return (Criteria) this;
        }

        public Criteria andNeedNumberLessThanOrEqualTo(Integer value) {
            addCriterion("need_number <=", value, "needNumber");
            return (Criteria) this;
        }

        public Criteria andNeedNumberIn(List<Integer> values) {
            addCriterion("need_number in", values, "needNumber");
            return (Criteria) this;
        }

        public Criteria andNeedNumberNotIn(List<Integer> values) {
            addCriterion("need_number not in", values, "needNumber");
            return (Criteria) this;
        }

        public Criteria andNeedNumberBetween(Integer value1, Integer value2) {
            addCriterion("need_number between", value1, value2, "needNumber");
            return (Criteria) this;
        }

        public Criteria andNeedNumberNotBetween(Integer value1, Integer value2) {
            addCriterion("need_number not between", value1, value2, "needNumber");
            return (Criteria) this;
        }

        public Criteria andPayTypeIsNull() {
            addCriterion("pay_type is null");
            return (Criteria) this;
        }

        public Criteria andPayTypeIsNotNull() {
            addCriterion("pay_type is not null");
            return (Criteria) this;
        }

        public Criteria andPayTypeEqualTo(Integer value) {
            addCriterion("pay_type =", value, "payType");
            return (Criteria) this;
        }

        public Criteria andPayTypeNotEqualTo(Integer value) {
            addCriterion("pay_type <>", value, "payType");
            return (Criteria) this;
        }

        public Criteria andPayTypeGreaterThan(Integer value) {
            addCriterion("pay_type >", value, "payType");
            return (Criteria) this;
        }

        public Criteria andPayTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("pay_type >=", value, "payType");
            return (Criteria) this;
        }

        public Criteria andPayTypeLessThan(Integer value) {
            addCriterion("pay_type <", value, "payType");
            return (Criteria) this;
        }

        public Criteria andPayTypeLessThanOrEqualTo(Integer value) {
            addCriterion("pay_type <=", value, "payType");
            return (Criteria) this;
        }

        public Criteria andPayTypeIn(List<Integer> values) {
            addCriterion("pay_type in", values, "payType");
            return (Criteria) this;
        }

        public Criteria andPayTypeNotIn(List<Integer> values) {
            addCriterion("pay_type not in", values, "payType");
            return (Criteria) this;
        }

        public Criteria andPayTypeBetween(Integer value1, Integer value2) {
            addCriterion("pay_type between", value1, value2, "payType");
            return (Criteria) this;
        }

        public Criteria andPayTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("pay_type not between", value1, value2, "payType");
            return (Criteria) this;
        }

        public Criteria andAppointImgsIsNull() {
            addCriterion("appoint_imgs is null");
            return (Criteria) this;
        }

        public Criteria andAppointImgsIsNotNull() {
            addCriterion("appoint_imgs is not null");
            return (Criteria) this;
        }

        public Criteria andAppointImgsEqualTo(String value) {
            addCriterion("appoint_imgs =", value, "appointImgs");
            return (Criteria) this;
        }

        public Criteria andAppointImgsNotEqualTo(String value) {
            addCriterion("appoint_imgs <>", value, "appointImgs");
            return (Criteria) this;
        }

        public Criteria andAppointImgsGreaterThan(String value) {
            addCriterion("appoint_imgs >", value, "appointImgs");
            return (Criteria) this;
        }

        public Criteria andAppointImgsGreaterThanOrEqualTo(String value) {
            addCriterion("appoint_imgs >=", value, "appointImgs");
            return (Criteria) this;
        }

        public Criteria andAppointImgsLessThan(String value) {
            addCriterion("appoint_imgs <", value, "appointImgs");
            return (Criteria) this;
        }

        public Criteria andAppointImgsLessThanOrEqualTo(String value) {
            addCriterion("appoint_imgs <=", value, "appointImgs");
            return (Criteria) this;
        }

        public Criteria andAppointImgsLike(String value) {
            addCriterion("appoint_imgs like", value, "appointImgs");
            return (Criteria) this;
        }

        public Criteria andAppointImgsNotLike(String value) {
            addCriterion("appoint_imgs not like", value, "appointImgs");
            return (Criteria) this;
        }

        public Criteria andAppointImgsIn(List<String> values) {
            addCriterion("appoint_imgs in", values, "appointImgs");
            return (Criteria) this;
        }

        public Criteria andAppointImgsNotIn(List<String> values) {
            addCriterion("appoint_imgs not in", values, "appointImgs");
            return (Criteria) this;
        }

        public Criteria andAppointImgsBetween(String value1, String value2) {
            addCriterion("appoint_imgs between", value1, value2, "appointImgs");
            return (Criteria) this;
        }

        public Criteria andAppointImgsNotBetween(String value1, String value2) {
            addCriterion("appoint_imgs not between", value1, value2, "appointImgs");
            return (Criteria) this;
        }

        public Criteria andRewardIsNull() {
            addCriterion("reward is null");
            return (Criteria) this;
        }

        public Criteria andRewardIsNotNull() {
            addCriterion("reward is not null");
            return (Criteria) this;
        }

        public Criteria andRewardEqualTo(Integer value) {
            addCriterion("reward =", value, "reward");
            return (Criteria) this;
        }

        public Criteria andRewardNotEqualTo(Integer value) {
            addCriterion("reward <>", value, "reward");
            return (Criteria) this;
        }

        public Criteria andRewardGreaterThan(Integer value) {
            addCriterion("reward >", value, "reward");
            return (Criteria) this;
        }

        public Criteria andRewardGreaterThanOrEqualTo(Integer value) {
            addCriterion("reward >=", value, "reward");
            return (Criteria) this;
        }

        public Criteria andRewardLessThan(Integer value) {
            addCriterion("reward <", value, "reward");
            return (Criteria) this;
        }

        public Criteria andRewardLessThanOrEqualTo(Integer value) {
            addCriterion("reward <=", value, "reward");
            return (Criteria) this;
        }

        public Criteria andRewardIn(List<Integer> values) {
            addCriterion("reward in", values, "reward");
            return (Criteria) this;
        }

        public Criteria andRewardNotIn(List<Integer> values) {
            addCriterion("reward not in", values, "reward");
            return (Criteria) this;
        }

        public Criteria andRewardBetween(Integer value1, Integer value2) {
            addCriterion("reward between", value1, value2, "reward");
            return (Criteria) this;
        }

        public Criteria andRewardNotBetween(Integer value1, Integer value2) {
            addCriterion("reward not between", value1, value2, "reward");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("state is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("state is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(Integer value) {
            addCriterion("state =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(Integer value) {
            addCriterion("state <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(Integer value) {
            addCriterion("state >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(Integer value) {
            addCriterion("state >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(Integer value) {
            addCriterion("state <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(Integer value) {
            addCriterion("state <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<Integer> values) {
            addCriterion("state in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<Integer> values) {
            addCriterion("state not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(Integer value1, Integer value2) {
            addCriterion("state between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(Integer value1, Integer value2) {
            addCriterion("state not between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andConfirmIdIsNull() {
            addCriterion("confirm_id is null");
            return (Criteria) this;
        }

        public Criteria andConfirmIdIsNotNull() {
            addCriterion("confirm_id is not null");
            return (Criteria) this;
        }

        public Criteria andConfirmIdEqualTo(Integer value) {
            addCriterion("confirm_id =", value, "confirmId");
            return (Criteria) this;
        }

        public Criteria andConfirmIdNotEqualTo(Integer value) {
            addCriterion("confirm_id <>", value, "confirmId");
            return (Criteria) this;
        }

        public Criteria andConfirmIdGreaterThan(Integer value) {
            addCriterion("confirm_id >", value, "confirmId");
            return (Criteria) this;
        }

        public Criteria andConfirmIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("confirm_id >=", value, "confirmId");
            return (Criteria) this;
        }

        public Criteria andConfirmIdLessThan(Integer value) {
            addCriterion("confirm_id <", value, "confirmId");
            return (Criteria) this;
        }

        public Criteria andConfirmIdLessThanOrEqualTo(Integer value) {
            addCriterion("confirm_id <=", value, "confirmId");
            return (Criteria) this;
        }

        public Criteria andConfirmIdIn(List<Integer> values) {
            addCriterion("confirm_id in", values, "confirmId");
            return (Criteria) this;
        }

        public Criteria andConfirmIdNotIn(List<Integer> values) {
            addCriterion("confirm_id not in", values, "confirmId");
            return (Criteria) this;
        }

        public Criteria andConfirmIdBetween(Integer value1, Integer value2) {
            addCriterion("confirm_id between", value1, value2, "confirmId");
            return (Criteria) this;
        }

        public Criteria andConfirmIdNotBetween(Integer value1, Integer value2) {
            addCriterion("confirm_id not between", value1, value2, "confirmId");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table appointment
     *
     * @mbggenerated do_not_delete_during_merge Wed Aug 21 16:35:07 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table appointment
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}