package com.meiyou.pojo;

import java.util.Date;

public class Cash {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash.id
     *
     * @mbggenerated Wed Aug 21 14:28:33 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash.cash_id
     *
     * @mbggenerated Wed Aug 21 14:28:33 CST 2019
     */
    private Integer cashId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash.cash_money
     *
     * @mbggenerated Wed Aug 21 14:28:33 CST 2019
     */
    private Integer cashMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash.cash_type
     *
     * @mbggenerated Wed Aug 21 14:28:33 CST 2019
     */
    private Integer cashType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash.state
     *
     * @mbggenerated Wed Aug 21 14:28:33 CST 2019
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash.create_time
     *
     * @mbggenerated Wed Aug 21 14:28:33 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash.update_time
     *
     * @mbggenerated Wed Aug 21 14:28:33 CST 2019
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash.id
     *
     * @return the value of cash.id
     *
     * @mbggenerated Wed Aug 21 14:28:33 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash.id
     *
     * @param id the value for cash.id
     *
     * @mbggenerated Wed Aug 21 14:28:33 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash.cash_id
     *
     * @return the value of cash.cash_id
     *
     * @mbggenerated Wed Aug 21 14:28:33 CST 2019
     */
    public Integer getCashId() {
        return cashId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash.cash_id
     *
     * @param cashId the value for cash.cash_id
     *
     * @mbggenerated Wed Aug 21 14:28:33 CST 2019
     */
    public void setCashId(Integer cashId) {
        this.cashId = cashId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash.cash_money
     *
     * @return the value of cash.cash_money
     *
     * @mbggenerated Wed Aug 21 14:28:33 CST 2019
     */
    public Integer getCashMoney() {
        return cashMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash.cash_money
     *
     * @param cashMoney the value for cash.cash_money
     *
     * @mbggenerated Wed Aug 21 14:28:33 CST 2019
     */
    public void setCashMoney(Integer cashMoney) {
        this.cashMoney = cashMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash.cash_type
     *
     * @return the value of cash.cash_type
     *
     * @mbggenerated Wed Aug 21 14:28:33 CST 2019
     */
    public Integer getCashType() {
        return cashType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash.cash_type
     *
     * @param cashType the value for cash.cash_type
     *
     * @mbggenerated Wed Aug 21 14:28:33 CST 2019
     */
    public void setCashType(Integer cashType) {
        this.cashType = cashType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash.state
     *
     * @return the value of cash.state
     *
     * @mbggenerated Wed Aug 21 14:28:33 CST 2019
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash.state
     *
     * @param state the value for cash.state
     *
     * @mbggenerated Wed Aug 21 14:28:33 CST 2019
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash.create_time
     *
     * @return the value of cash.create_time
     *
     * @mbggenerated Wed Aug 21 14:28:33 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash.create_time
     *
     * @param createTime the value for cash.create_time
     *
     * @mbggenerated Wed Aug 21 14:28:33 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash.update_time
     *
     * @return the value of cash.update_time
     *
     * @mbggenerated Wed Aug 21 14:28:33 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash.update_time
     *
     * @param updateTime the value for cash.update_time
     *
     * @mbggenerated Wed Aug 21 14:28:33 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}