package com.meiyou.pojo;
import java.io.Serializable;
import java.util.Date;

public class ClubStar implements Serializable {
    private Integer id;
    private Integer clubId;
    private Integer evaluationId;
    private Integer star;
    private Date createTime;
    private Date updateTime;

    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_star.id
     *
     * @param id the value for club_star.id
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_star.club_id
     *
     * @return the value of club_star.club_id
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    public Integer getClubId() {
        return clubId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_star.club_id
     *
     * @param clubId the value for club_star.club_id
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    public void setClubId(Integer clubId) {
        this.clubId = clubId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_star.evaluation_id
     *
     * @return the value of club_star.evaluation_id
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    public Integer getEvaluationId() {
        return evaluationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_star.evaluation_id
     *
     * @param evaluationId the value for club_star.evaluation_id
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    public void setEvaluationId(Integer evaluationId) {
        this.evaluationId = evaluationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_star.star
     *
     * @return the value of club_star.star
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    public Integer getStar() {
        return star;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_star.star
     *
     * @param star the value for club_star.star
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    public void setStar(Integer star) {
        this.star = star;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_star.create_time
     *
     * @return the value of club_star.create_time
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_star.create_time
     *
     * @param createTime the value for club_star.create_time
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_star.update_time
     *
     * @return the value of club_star.update_time
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_star.update_time
     *
     * @param updateTime the value for club_star.update_time
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}