package com.meiyou.pojo;

import java.util.Date;

public class Club {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column club.id
     *
     * @mbggenerated Wed Aug 21 14:28:33 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column club.create_time
     *
     * @mbggenerated Wed Aug 21 14:28:33 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column club.update_time
     *
     * @mbggenerated Wed Aug 21 14:28:33 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column club.publish_id
     *
     * @mbggenerated Wed Aug 21 14:28:33 CST 2019
     */
    private Integer publishId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column club.imgs_url
     *
     * @mbggenerated Wed Aug 21 14:28:33 CST 2019
     */
    private String imgsUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column club.project_name
     *
     * @mbggenerated Wed Aug 21 14:28:33 CST 2019
     */
    private String projectName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column club.project_desc
     *
     * @mbggenerated Wed Aug 21 14:28:33 CST 2019
     */
    private String projectDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column club.project_address
     *
     * @mbggenerated Wed Aug 21 14:28:33 CST 2019
     */
    private String projectAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column club.project_price
     *
     * @mbggenerated Wed Aug 21 14:28:33 CST 2019
     */
    private Integer projectPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column club.market_price
     *
     * @mbggenerated Wed Aug 21 14:28:33 CST 2019
     */
    private Integer marketPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column club.out_time
     *
     * @mbggenerated Wed Aug 21 14:28:33 CST 2019
     */
    private Date outTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column club.state
     *
     * @mbggenerated Wed Aug 21 14:28:33 CST 2019
     */
    private Integer state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club.id
     *
     * @return the value of club.id
     *
     * @mbggenerated Wed Aug 21 14:28:33 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club.id
     *
     * @param id the value for club.id
     *
     * @mbggenerated Wed Aug 21 14:28:33 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club.create_time
     *
     * @return the value of club.create_time
     *
     * @mbggenerated Wed Aug 21 14:28:33 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club.create_time
     *
     * @param createTime the value for club.create_time
     *
     * @mbggenerated Wed Aug 21 14:28:33 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club.update_time
     *
     * @return the value of club.update_time
     *
     * @mbggenerated Wed Aug 21 14:28:33 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club.update_time
     *
     * @param updateTime the value for club.update_time
     *
     * @mbggenerated Wed Aug 21 14:28:33 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club.publish_id
     *
     * @return the value of club.publish_id
     *
     * @mbggenerated Wed Aug 21 14:28:33 CST 2019
     */
    public Integer getPublishId() {
        return publishId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club.publish_id
     *
     * @param publishId the value for club.publish_id
     *
     * @mbggenerated Wed Aug 21 14:28:33 CST 2019
     */
    public void setPublishId(Integer publishId) {
        this.publishId = publishId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club.imgs_url
     *
     * @return the value of club.imgs_url
     *
     * @mbggenerated Wed Aug 21 14:28:33 CST 2019
     */
    public String getImgsUrl() {
        return imgsUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club.imgs_url
     *
     * @param imgsUrl the value for club.imgs_url
     *
     * @mbggenerated Wed Aug 21 14:28:33 CST 2019
     */
    public void setImgsUrl(String imgsUrl) {
        this.imgsUrl = imgsUrl == null ? null : imgsUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club.project_name
     *
     * @return the value of club.project_name
     *
     * @mbggenerated Wed Aug 21 14:28:33 CST 2019
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club.project_name
     *
     * @param projectName the value for club.project_name
     *
     * @mbggenerated Wed Aug 21 14:28:33 CST 2019
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName == null ? null : projectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club.project_desc
     *
     * @return the value of club.project_desc
     *
     * @mbggenerated Wed Aug 21 14:28:33 CST 2019
     */
    public String getProjectDesc() {
        return projectDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club.project_desc
     *
     * @param projectDesc the value for club.project_desc
     *
     * @mbggenerated Wed Aug 21 14:28:33 CST 2019
     */
    public void setProjectDesc(String projectDesc) {
        this.projectDesc = projectDesc == null ? null : projectDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club.project_address
     *
     * @return the value of club.project_address
     *
     * @mbggenerated Wed Aug 21 14:28:33 CST 2019
     */
    public String getProjectAddress() {
        return projectAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club.project_address
     *
     * @param projectAddress the value for club.project_address
     *
     * @mbggenerated Wed Aug 21 14:28:33 CST 2019
     */
    public void setProjectAddress(String projectAddress) {
        this.projectAddress = projectAddress == null ? null : projectAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club.project_price
     *
     * @return the value of club.project_price
     *
     * @mbggenerated Wed Aug 21 14:28:33 CST 2019
     */
    public Integer getProjectPrice() {
        return projectPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club.project_price
     *
     * @param projectPrice the value for club.project_price
     *
     * @mbggenerated Wed Aug 21 14:28:33 CST 2019
     */
    public void setProjectPrice(Integer projectPrice) {
        this.projectPrice = projectPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club.market_price
     *
     * @return the value of club.market_price
     *
     * @mbggenerated Wed Aug 21 14:28:33 CST 2019
     */
    public Integer getMarketPrice() {
        return marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club.market_price
     *
     * @param marketPrice the value for club.market_price
     *
     * @mbggenerated Wed Aug 21 14:28:33 CST 2019
     */
    public void setMarketPrice(Integer marketPrice) {
        this.marketPrice = marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club.out_time
     *
     * @return the value of club.out_time
     *
     * @mbggenerated Wed Aug 21 14:28:33 CST 2019
     */
    public Date getOutTime() {
        return outTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club.out_time
     *
     * @param outTime the value for club.out_time
     *
     * @mbggenerated Wed Aug 21 14:28:33 CST 2019
     */
    public void setOutTime(Date outTime) {
        this.outTime = outTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club.state
     *
     * @return the value of club.state
     *
     * @mbggenerated Wed Aug 21 14:28:33 CST 2019
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club.state
     *
     * @param state the value for club.state
     *
     * @mbggenerated Wed Aug 21 14:28:33 CST 2019
     */
    public void setState(Integer state) {
        this.state = state;
    }
}