package com.meiyou.pojo;

import java.io.Serializable;
import java.util.Date;

public class CommentLike implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_like.id
     *
     * @mbggenerated Fri Aug 23 17:39:47 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_like.create_time
     *
     * @mbggenerated Fri Aug 23 17:39:47 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_like.update_time
     *
     * @mbggenerated Fri Aug 23 17:39:47 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_like.comment_id
     *
     * @mbggenerated Fri Aug 23 17:39:47 CST 2019
     */
    private Integer commentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_like.like_id
     *
     * @mbggenerated Fri Aug 23 17:39:47 CST 2019
     */
    private Integer likeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_like.bool_see
     *
     * @mbggenerated Fri Aug 23 17:39:47 CST 2019
     */
    private Boolean boolSee;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_like.id
     *
     * @return the value of comment_like.id
     *
     * @mbggenerated Fri Aug 23 17:39:47 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_like.id
     *
     * @param id the value for comment_like.id
     *
     * @mbggenerated Fri Aug 23 17:39:47 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_like.create_time
     *
     * @return the value of comment_like.create_time
     *
     * @mbggenerated Fri Aug 23 17:39:47 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_like.create_time
     *
     * @param createTime the value for comment_like.create_time
     *
     * @mbggenerated Fri Aug 23 17:39:47 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_like.update_time
     *
     * @return the value of comment_like.update_time
     *
     * @mbggenerated Fri Aug 23 17:39:47 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_like.update_time
     *
     * @param updateTime the value for comment_like.update_time
     *
     * @mbggenerated Fri Aug 23 17:39:47 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_like.comment_id
     *
     * @return the value of comment_like.comment_id
     *
     * @mbggenerated Fri Aug 23 17:39:47 CST 2019
     */
    public Integer getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_like.comment_id
     *
     * @param commentId the value for comment_like.comment_id
     *
     * @mbggenerated Fri Aug 23 17:39:47 CST 2019
     */
    public void setCommentId(Integer commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_like.like_id
     *
     * @return the value of comment_like.like_id
     *
     * @mbggenerated Fri Aug 23 17:39:47 CST 2019
     */
    public Integer getLikeId() {
        return likeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_like.like_id
     *
     * @param likeId the value for comment_like.like_id
     *
     * @mbggenerated Fri Aug 23 17:39:47 CST 2019
     */
    public void setLikeId(Integer likeId) {
        this.likeId = likeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_like.bool_see
     *
     * @return the value of comment_like.bool_see
     *
     * @mbggenerated Fri Aug 23 17:39:47 CST 2019
     */
    public Boolean getBoolSee() {
        return boolSee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_like.bool_see
     *
     * @param boolSee the value for comment_like.bool_see
     *
     * @mbggenerated Fri Aug 23 17:39:47 CST 2019
     */
    public void setBoolSee(Boolean boolSee) {
        this.boolSee = boolSee;
    }
}