package com.meiyou.pojo;

import java.util.Date;

public class Read {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column read.id
     *
     * @mbggenerated Wed Aug 21 11:49:14 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column read.create_time
     *
     * @mbggenerated Wed Aug 21 11:49:14 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column read.update_time
     *
     * @mbggenerated Wed Aug 21 11:49:14 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column read.activity_id
     *
     * @mbggenerated Wed Aug 21 11:49:14 CST 2019
     */
    private Integer activityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column read.reader_id
     *
     * @mbggenerated Wed Aug 21 11:49:14 CST 2019
     */
    private Integer readerId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column read.id
     *
     * @return the value of read.id
     *
     * @mbggenerated Wed Aug 21 11:49:14 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column read.id
     *
     * @param id the value for read.id
     *
     * @mbggenerated Wed Aug 21 11:49:14 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column read.create_time
     *
     * @return the value of read.create_time
     *
     * @mbggenerated Wed Aug 21 11:49:14 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column read.create_time
     *
     * @param createTime the value for read.create_time
     *
     * @mbggenerated Wed Aug 21 11:49:14 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column read.update_time
     *
     * @return the value of read.update_time
     *
     * @mbggenerated Wed Aug 21 11:49:14 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column read.update_time
     *
     * @param updateTime the value for read.update_time
     *
     * @mbggenerated Wed Aug 21 11:49:14 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column read.activity_id
     *
     * @return the value of read.activity_id
     *
     * @mbggenerated Wed Aug 21 11:49:14 CST 2019
     */
    public Integer getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column read.activity_id
     *
     * @param activityId the value for read.activity_id
     *
     * @mbggenerated Wed Aug 21 11:49:14 CST 2019
     */
    public void setActivityId(Integer activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column read.reader_id
     *
     * @return the value of read.reader_id
     *
     * @mbggenerated Wed Aug 21 11:49:14 CST 2019
     */
    public Integer getReaderId() {
        return readerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column read.reader_id
     *
     * @param readerId the value for read.reader_id
     *
     * @mbggenerated Wed Aug 21 11:49:14 CST 2019
     */
    public void setReaderId(Integer readerId) {
        this.readerId = readerId;
    }
}