package com.meiyou.pojo;

import java.io.Serializable;
import java.util.Date;

public class RedPacket implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_packet.id
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_packet.money
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    private Integer money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_packet.sender_id
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    private Integer senderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_packet.receive_id
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    private Integer receiveId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_packet.state
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_packet.content
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_packet.create_time
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_packet.update_time
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_packet.id
     *
     * @return the value of red_packet.id
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_packet.id
     *
     * @param id the value for red_packet.id
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_packet.money
     *
     * @return the value of red_packet.money
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    public Integer getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_packet.money
     *
     * @param money the value for red_packet.money
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    public void setMoney(Integer money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_packet.sender_id
     *
     * @return the value of red_packet.sender_id
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    public Integer getSenderId() {
        return senderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_packet.sender_id
     *
     * @param senderId the value for red_packet.sender_id
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    public void setSenderId(Integer senderId) {
        this.senderId = senderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_packet.receive_id
     *
     * @return the value of red_packet.receive_id
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    public Integer getReceiveId() {
        return receiveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_packet.receive_id
     *
     * @param receiveId the value for red_packet.receive_id
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    public void setReceiveId(Integer receiveId) {
        this.receiveId = receiveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_packet.state
     *
     * @return the value of red_packet.state
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_packet.state
     *
     * @param state the value for red_packet.state
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_packet.content
     *
     * @return the value of red_packet.content
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_packet.content
     *
     * @param content the value for red_packet.content
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_packet.create_time
     *
     * @return the value of red_packet.create_time
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_packet.create_time
     *
     * @param createTime the value for red_packet.create_time
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_packet.update_time
     *
     * @return the value of red_packet.update_time
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_packet.update_time
     *
     * @param updateTime the value for red_packet.update_time
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}