package com.meiyou.pojo;

import java.io.Serializable;
import java.util.Date;

public class Share implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share.id
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share.create_time
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share.update_time
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share.people_id
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    private Integer peopleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share.by_people_id
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    private Integer byPeopleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share.share_money
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    private Integer shareMoney;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share.id
     *
     * @return the value of share.id
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share.id
     *
     * @param id the value for share.id
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share.create_time
     *
     * @return the value of share.create_time
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share.create_time
     *
     * @param createTime the value for share.create_time
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share.update_time
     *
     * @return the value of share.update_time
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share.update_time
     *
     * @param updateTime the value for share.update_time
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share.people_id
     *
     * @return the value of share.people_id
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    public Integer getPeopleId() {
        return peopleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share.people_id
     *
     * @param peopleId the value for share.people_id
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    public void setPeopleId(Integer peopleId) {
        this.peopleId = peopleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share.by_people_id
     *
     * @return the value of share.by_people_id
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    public Integer getByPeopleId() {
        return byPeopleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share.by_people_id
     *
     * @param byPeopleId the value for share.by_people_id
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    public void setByPeopleId(Integer byPeopleId) {
        this.byPeopleId = byPeopleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share.share_money
     *
     * @return the value of share.share_money
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    public Integer getShareMoney() {
        return shareMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share.share_money
     *
     * @param shareMoney the value for share.share_money
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    public void setShareMoney(Integer shareMoney) {
        this.shareMoney = shareMoney;
    }
}