package com.meiyou.pojo;

import java.io.Serializable;
import java.util.Date;

public class ShopBuy implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_buy.id
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_buy.create_time
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_buy.update_time
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_buy.guide_id
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    private Integer guideId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_buy.buyer_id
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    private Integer buyerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_buy.state
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_buy.time
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    private Integer time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_buy.id
     *
     * @return the value of shop_buy.id
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_buy.id
     *
     * @param id the value for shop_buy.id
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_buy.create_time
     *
     * @return the value of shop_buy.create_time
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_buy.create_time
     *
     * @param createTime the value for shop_buy.create_time
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_buy.update_time
     *
     * @return the value of shop_buy.update_time
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_buy.update_time
     *
     * @param updateTime the value for shop_buy.update_time
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_buy.guide_id
     *
     * @return the value of shop_buy.guide_id
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    public Integer getGuideId() {
        return guideId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_buy.guide_id
     *
     * @param guideId the value for shop_buy.guide_id
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    public void setGuideId(Integer guideId) {
        this.guideId = guideId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_buy.buyer_id
     *
     * @return the value of shop_buy.buyer_id
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    public Integer getBuyerId() {
        return buyerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_buy.buyer_id
     *
     * @param buyerId the value for shop_buy.buyer_id
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    public void setBuyerId(Integer buyerId) {
        this.buyerId = buyerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_buy.state
     *
     * @return the value of shop_buy.state
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_buy.state
     *
     * @param state the value for shop_buy.state
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_buy.time
     *
     * @return the value of shop_buy.time
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    public Integer getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_buy.time
     *
     * @param time the value for shop_buy.time
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    public void setTime(Integer time) {
        this.time = time;
    }
}