package com.meiyou.pojo;

import java.io.Serializable;
import java.util.Date;

public class TourAsk implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tour_ask.id
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tour_ask.create_time
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tour_ask.update_time
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tour_ask.appoint_id
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    private Integer appointId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tour_ask.asker_id
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    private Integer askerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tour_ask.ask_state0
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    private Integer askState0;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tour_ask.id
     *
     * @return the value of tour_ask.id
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tour_ask.id
     *
     * @param id the value for tour_ask.id
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tour_ask.create_time
     *
     * @return the value of tour_ask.create_time
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tour_ask.create_time
     *
     * @param createTime the value for tour_ask.create_time
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tour_ask.update_time
     *
     * @return the value of tour_ask.update_time
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tour_ask.update_time
     *
     * @param updateTime the value for tour_ask.update_time
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tour_ask.appoint_id
     *
     * @return the value of tour_ask.appoint_id
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    public Integer getAppointId() {
        return appointId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tour_ask.appoint_id
     *
     * @param appointId the value for tour_ask.appoint_id
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    public void setAppointId(Integer appointId) {
        this.appointId = appointId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tour_ask.asker_id
     *
     * @return the value of tour_ask.asker_id
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    public Integer getAskerId() {
        return askerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tour_ask.asker_id
     *
     * @param askerId the value for tour_ask.asker_id
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    public void setAskerId(Integer askerId) {
        this.askerId = askerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tour_ask.ask_state0
     *
     * @return the value of tour_ask.ask_state0
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    public Integer getAskState0() {
        return askState0;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tour_ask.ask_state0
     *
     * @param askState0 the value for tour_ask.ask_state0
     *
     * @mbggenerated Wed Aug 21 16:35:07 CST 2019
     */
    public void setAskState0(Integer askState0) {
        this.askState0 = askState0;
    }
}