package com.meiyou.pojo;

import java.util.Date;

public class UserReport {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_report.id
     *
     * @mbggenerated Fri Aug 30 14:41:10 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_report.create_time
     *
     * @mbggenerated Fri Aug 30 14:41:10 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_report.update_time
     *
     * @mbggenerated Fri Aug 30 14:41:10 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_report.reporter_id
     *
     * @mbggenerated Fri Aug 30 14:41:10 CST 2019
     */
    private Integer reporterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_report.reported_person_id
     *
     * @mbggenerated Fri Aug 30 14:41:10 CST 2019
     */
    private Integer reportedPersonId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_report.type
     *
     * @mbggenerated Fri Aug 30 14:41:10 CST 2019
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_report.content
     *
     * @mbggenerated Fri Aug 30 14:41:10 CST 2019
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_report.id
     *
     * @return the value of user_report.id
     *
     * @mbggenerated Fri Aug 30 14:41:10 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_report.id
     *
     * @param id the value for user_report.id
     *
     * @mbggenerated Fri Aug 30 14:41:10 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_report.create_time
     *
     * @return the value of user_report.create_time
     *
     * @mbggenerated Fri Aug 30 14:41:10 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_report.create_time
     *
     * @param createTime the value for user_report.create_time
     *
     * @mbggenerated Fri Aug 30 14:41:10 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_report.update_time
     *
     * @return the value of user_report.update_time
     *
     * @mbggenerated Fri Aug 30 14:41:10 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_report.update_time
     *
     * @param updateTime the value for user_report.update_time
     *
     * @mbggenerated Fri Aug 30 14:41:10 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_report.reporter_id
     *
     * @return the value of user_report.reporter_id
     *
     * @mbggenerated Fri Aug 30 14:41:10 CST 2019
     */
    public Integer getReporterId() {
        return reporterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_report.reporter_id
     *
     * @param reporterId the value for user_report.reporter_id
     *
     * @mbggenerated Fri Aug 30 14:41:10 CST 2019
     */
    public void setReporterId(Integer reporterId) {
        this.reporterId = reporterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_report.reported_person_id
     *
     * @return the value of user_report.reported_person_id
     *
     * @mbggenerated Fri Aug 30 14:41:10 CST 2019
     */
    public Integer getReportedPersonId() {
        return reportedPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_report.reported_person_id
     *
     * @param reportedPersonId the value for user_report.reported_person_id
     *
     * @mbggenerated Fri Aug 30 14:41:10 CST 2019
     */
    public void setReportedPersonId(Integer reportedPersonId) {
        this.reportedPersonId = reportedPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_report.type
     *
     * @return the value of user_report.type
     *
     * @mbggenerated Fri Aug 30 14:41:10 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_report.type
     *
     * @param type the value for user_report.type
     *
     * @mbggenerated Fri Aug 30 14:41:10 CST 2019
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_report.content
     *
     * @return the value of user_report.content
     *
     * @mbggenerated Fri Aug 30 14:41:10 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_report.content
     *
     * @param content the value for user_report.content
     *
     * @mbggenerated Fri Aug 30 14:41:10 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}