package com.meiyou.pojo;

import java.util.Date;

public class VideoChat {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_chat.id
     *
     * @mbggenerated Sat Aug 24 22:37:36 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_chat.sender_account
     *
     * @mbggenerated Sat Aug 24 22:37:36 CST 2019
     */
    private String senderAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_chat.receiver_account
     *
     * @mbggenerated Sat Aug 24 22:37:36 CST 2019
     */
    private String receiverAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_chat.state
     *
     * @mbggenerated Sat Aug 24 22:37:36 CST 2019
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_chat.money
     *
     * @mbggenerated Sat Aug 24 22:37:36 CST 2019
     */
    private Double money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_chat.channel_Id
     *
     * @mbggenerated Sat Aug 24 22:37:36 CST 2019
     */
    private String channelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_chat.greate_time
     *
     * @mbggenerated Sat Aug 24 22:37:36 CST 2019
     */
    private Date greateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_chat.update_time
     *
     * @mbggenerated Sat Aug 24 22:37:36 CST 2019
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_chat.id
     *
     * @return the value of video_chat.id
     *
     * @mbggenerated Sat Aug 24 22:37:36 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_chat.id
     *
     * @param id the value for video_chat.id
     *
     * @mbggenerated Sat Aug 24 22:37:36 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_chat.sender_account
     *
     * @return the value of video_chat.sender_account
     *
     * @mbggenerated Sat Aug 24 22:37:36 CST 2019
     */
    public String getSenderAccount() {
        return senderAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_chat.sender_account
     *
     * @param senderAccount the value for video_chat.sender_account
     *
     * @mbggenerated Sat Aug 24 22:37:36 CST 2019
     */
    public void setSenderAccount(String senderAccount) {
        this.senderAccount = senderAccount == null ? null : senderAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_chat.receiver_account
     *
     * @return the value of video_chat.receiver_account
     *
     * @mbggenerated Sat Aug 24 22:37:36 CST 2019
     */
    public String getReceiverAccount() {
        return receiverAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_chat.receiver_account
     *
     * @param receiverAccount the value for video_chat.receiver_account
     *
     * @mbggenerated Sat Aug 24 22:37:36 CST 2019
     */
    public void setReceiverAccount(String receiverAccount) {
        this.receiverAccount = receiverAccount == null ? null : receiverAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_chat.state
     *
     * @return the value of video_chat.state
     *
     * @mbggenerated Sat Aug 24 22:37:36 CST 2019
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_chat.state
     *
     * @param state the value for video_chat.state
     *
     * @mbggenerated Sat Aug 24 22:37:36 CST 2019
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_chat.money
     *
     * @return the value of video_chat.money
     *
     * @mbggenerated Sat Aug 24 22:37:36 CST 2019
     */
    public Double getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_chat.money
     *
     * @param money the value for video_chat.money
     *
     * @mbggenerated Sat Aug 24 22:37:36 CST 2019
     */
    public void setMoney(Double money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_chat.channel_Id
     *
     * @return the value of video_chat.channel_Id
     *
     * @mbggenerated Sat Aug 24 22:37:36 CST 2019
     */
    public String getChannelId() {
        return channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_chat.channel_Id
     *
     * @param channelId the value for video_chat.channel_Id
     *
     * @mbggenerated Sat Aug 24 22:37:36 CST 2019
     */
    public void setChannelId(String channelId) {
        this.channelId = channelId == null ? null : channelId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_chat.greate_time
     *
     * @return the value of video_chat.greate_time
     *
     * @mbggenerated Sat Aug 24 22:37:36 CST 2019
     */
    public Date getGreateTime() {
        return greateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_chat.greate_time
     *
     * @param greateTime the value for video_chat.greate_time
     *
     * @mbggenerated Sat Aug 24 22:37:36 CST 2019
     */
    public void setGreateTime(Date greateTime) {
        this.greateTime = greateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_chat.update_time
     *
     * @return the value of video_chat.update_time
     *
     * @mbggenerated Sat Aug 24 22:37:36 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_chat.update_time
     *
     * @param updateTime the value for video_chat.update_time
     *
     * @mbggenerated Sat Aug 24 22:37:36 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}